### ISSUE TITLE
segfault after ~5 times start & stop vpn

### ISSUE THREAD

**Issue by mokhtarabadi** [eycorsican/aleaf#14]
Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 4921 (Thread-12), pid 4451 (f.example.aleaf)

**Comment by mokhtarabadi** [comment]
I think problem is about closing VPN service file descriptor in rust (not sure yet)

@eycorsican did know how I can trace this?

**Comment by eycorsican** [comment]
No idea, don't have time to investigate this issue.

**Comment by Xx0101** [comment]
I have the same problem. Is there any way to solve it?

**Comment by giftedunicorn** [comment]
Don't press the run and stop too fast. Use a disable flag to freeze the button for 3 seconds or something.

**Comment by mokhtarabadi** [comment]
I tested this, even if I press the start / stop button with a delay, the program crashes

**Comment by sayhell** [comment]
same there, after run leaf crash immediately with:

```
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 12774 (Thread-3), pid 1646 (f.example.aleaf)
```

**Comment by mokhtarabadi** [comment]
now I run VPN service in another process instead app main process, and when need stop, also I kill the other process, I think currently this workaround works

**Comment by Xx0101** [comment]
> now I run VPN service in another process instead app main process, and when need stop, also I kill the other process, I think currently this workaround works

I've also tried to open a process, but when leaf is started frequently in the new one, direct connection and agent will be invalid

**Comment by mokhtarabadi** [comment]
> > now I run VPN service in another process instead app main process, and when need stop, also I kill the other process, I think currently this workaround works
> 
> I've also tried to open a process, but when leaf is started process in the new one, direct connection and agent will be invalid

how you run a new process?
I also put a 3 seconds delay between stop/start

**Comment by Xx0101** [comment]
> > > now I run VPN service in another process instead app main process, and when need stop, also I kill the other process, I think currently this workaround works
> > 
> > 
> > I've also tried to open a process, but when leaf is started process in the new one, direct connection and agent will be invalid
> 
> how you run a new process?
> I also put a 3 seconds delay between stop/start

Process is added to AndroidManifest's Simpleservice

**Comment by lucky-sheep** [comment]
> > > > now I run VPN service in another process instead app main process, and when need stop, also I kill the other process, I think currently this workaround works
> > > 
> > > 
> > > I've also tried to open a process, but when leaf is started process in the new one, direct connection and agent will be invalid
> > 
> > 
> > how you run a new process?
> > I also put a 3 seconds delay between stop/start
> 
> Process is added to AndroidManifest's Simpleservice
Without delay, will HTTP request fail？

**Comment by mokhtarabadi** [comment]
> > now I run VPN service in another process instead app main process, and when need stop, also I kill the other process, I think currently this workaround works
> 
> I've also tried to open a process, but when leaf is started process in the new one, direct connection and agent will be invalid

I test direct and proxy connection when leaf running in new process and everything works fine

Currently I use leaf in this app:
https://play.google.com/store/apps/details?id=org.hypervpn.android

Currently source code not open...

**Comment by Xx0101** [comment]
> > > now I run VPN service in another process instead app main process, and when need stop, also I kill the other process, I think currently this workaround works
> > 
> > 
> > I've also tried to open a process, but when leaf is started process in the new one, direct connection and agent will be invalid
> 
> I test direct and proxy connection when leaf running in new process and everything works fine
> 
> Currently I use leaf in this app:
> https://play.google.com/store/apps/details?id=org.hypervpn.android
> 
> Currently source code not open...

I found that the Android release package will fail to resolve the DNS (failed: resolve address failed), but debug is OK. How do you solve this problem

**Comment by Xx0101** [comment]
> > > > now I run VPN service in another process instead app main process, and when need stop, also I kill the other process, I think currently this workaround works
> > > 
> > > 
> > > I've also tried to open a process, but when leaf is started process in the new one, direct connection and agent will be invalid
> > 
> > 
> > I test direct and proxy connection when leaf running in new process and everything works fine
> > Currently I use leaf in this app:
> > https://play.google.com/store/apps/details?id=org.hypervpn.android
> > Currently source code not open...
> 
> I found that the Android release package will fail to resolve the DNS (failed: resolve address failed), but debug is OK. How do you solve this problem

In the realase packaging environment of gradle, I successfully added debuggable true

**Comment by nahddw** [comment]
@mokhtarabadi 
Hi Bro
Has this problem been resolved? how is the progress?

**Comment by mokhtarabadi** [comment]
Hey @nahddw 
Just wait 3 seconds between the start and stop, also kill the second process after stop which leaf run on that

**Comment by nahddw** [comment]
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe8eadebe5b3cd992 in tid 14776 (Thread-4), pid 14688 (f.example.aleaf)

I turn on the VPN, wait a few minutes and turn it off again.
app will crash.
Bro. What is the problem? 
@mokhtarabadi

**Comment by nahddw** [comment]
> Hey @nahddw
> Just wait 3 seconds between the start and stop, also kill the second process after stop which leaf run on that

thank you.

**Comment by nahddw** [comment]
Test the screen off for 1-2 hours wake up the phone again vpn normal use.
The test turns off the screen for one night or longer, wakes up the phone again, vpn cannot be used, and the phone has no network.
Bro you have encountered this situation?
@mokhtarabadi

**Comment by mokhtarabadi** [comment]
I didn't test this, my app is https://play.google.com/store/apps/details?id=org.hypervpn.android, you can test it too (and give me results thanks)

**Comment by azhm** [comment]
Ok i will tell you after the test.
@mokhtarabadi

**Comment by nahddw** [comment]
Ok i will tell you after the test.
@mokhtarabadi
