### ISSUE TITLE
failed: resolve address failed

### ISSUE THREAD

**Issue by Xx0101** [eycorsican/aleaf#16]
I found that the Android release package will fail to resolve the DNS (failed: resolve address failed), but debug is OK. 
In the realase packaging environment of gradle, I successfully added debuggable true

**Comment by mokhtarabadi** [comment]
if you can add output property to log section in your leaf config, and test release mode again and share logs here, also set log level to trace, for example:
```json
  "log": {
    "level": "trace",
    "output": "/data/user/0/com.leaf.example.aleaf/files/leaf.log"
  },
```
also, the device must be rooted, to get this file from a released version
