### ISSUE TITLE
java.io.IOException: accept failed: EBADF (Bad file descriptor)

### ISSUE THREAD

**Issue by lucky-sheep** [eycorsican/aleaf#17]
java.io.IOException: accept failed: EBADF (Bad file descriptor)

**Comment by mokhtarabadi** [comment]
put protectThread inside a loop while, so local socket will reconnect if failed

**Comment by lucky-sheep** [comment]
> put protectThread inside a loop while, so local socket will reconnect if failed

protectThread = thread(start = true)  {
            val localSocket = LocalSocket()
            localSocket.bind(LocalSocketAddress(protectPath, LocalSocketAddress.Namespace.FILESYSTEM))
            val socket = LocalServerSocket(localSocket.fileDescriptor)
            var buffer = ByteBuffer.allocate(4)
            try {
                while (true) {
                    val stream = socket.accept()
                    buffer.clear()
                    val n = stream.inputStream.read(buffer.array())
                    if (n == 4) {
                        var fd = buffer.getInt()
                        if (!this.protect(fd)) {
                            println("protect failed")
                        }
                        buffer.clear()
                        buffer.putInt(0)
                    } else {
                        buffer.clear()
                        buffer.putInt(1)
                    }
                    stream.outputStream.write(buffer.array())
                }
            } catch (e: IOException) {
                println("${e}1111111111111")
            }
        }

Sorry, I don't quite understand what you mean. I think there is a while loop in localsocket

**Comment by mokhtarabadi** [comment]
Hey @lucky-sheep
did you fix that?
I mean put LocalSocket inside a while, so when failed, a new one will created, for example, my protector thread code is: 
```java
public class ProtectorThread extends Thread {

    @Setter
    private MainService mainService;
    private LocalServerSocket localServerSocket;

    private final ExecutorService executorService = Executors.newFixedThreadPool(4);

    public void stopSelf() {
        executorService.shutdown();

        try {
            if (localServerSocket != null) {
                localServerSocket.close();
                localServerSocket = null;
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        interrupt();
    }

    @Override
    public void run() {
        super.run();

        do {
            File protectFile = new File(MainApplication.applicationContext.getFilesDir(), "protect_path.socket");
            if (protectFile.exists()) {
                boolean removed = protectFile.delete();
                log.debug("old socket removed? {}", removed);
            }

            try {
                LocalSocket localSocket = new LocalSocket();
                localSocket.bind(new LocalSocketAddress(protectFile.getAbsolutePath(), LocalSocketAddress.Namespace.FILESYSTEM));
                localServerSocket = new LocalServerSocket(localSocket.getFileDescriptor());

                while (!Thread.interrupted()) {
                    log.trace("wait for fd");

                    LocalSocket socket = localServerSocket.accept();

                    if (!executorService.isShutdown() && !executorService.isTerminated()) {
                        executorService.execute(() -> {
                            try {
                                DataInputStream inputStream = new DataInputStream(socket.getInputStream());
                                DataOutputStream outputStream = new DataOutputStream(socket.getOutputStream());

                                int fd = inputStream.readInt();

                                int success = 1;
                                if (!mainService.protect(fd)) {
                                    log.error("protect failed");
                                } else {
                                    success = 0;
                                }

                                outputStream.writeInt(success);

                                socket.close();
                            } catch (IOException e) {
                                e.printStackTrace();
                            }
                        });
                    }
                }

                log.info("loop broke");
            } catch (IOException e) {
                e.printStackTrace();
            }

            log.info("protector exit");
        } while (mainService.isAlive());
    }
}
```

**Comment by Xx0101** [comment]
> Hey @lucky-sheep
> did you fix that?
> I mean put LocalSocket inside a while, so when failed, a new one will created, for example, my protector thread code is:
> 
> ```java
> public class ProtectorThread extends Thread {
> 
>     @Setter
>     private MainService mainService;
>     private LocalServerSocket localServerSocket;
> 
>     private final ExecutorService executorService = Executors.newFixedThreadPool(4);
> 
>     public void stopSelf() {
>         executorService.shutdown();
> 
>         try {
>             if (localServerSocket != null) {
>                 localServerSocket.close();
>                 localServerSocket = null;
>             }
>         } catch (IOException e) {
>             e.printStackTrace();
>         }
> 
>         interrupt();
>     }
> 
>     @Override
>     public void run() {
>         super.run();
> 
>         do {
>             File protectFile = new File(MainApplication.applicationContext.getFilesDir(), "protect_path.socket");
>             if (protectFile.exists()) {
>                 boolean removed = protectFile.delete();
>                 log.debug("old socket removed? {}", removed);
>             }
> 
>             try {
>                 LocalSocket localSocket = new LocalSocket();
>                 localSocket.bind(new LocalSocketAddress(protectFile.getAbsolutePath(), LocalSocketAddress.Namespace.FILESYSTEM));
>                 localServerSocket = new LocalServerSocket(localSocket.getFileDescriptor());
> 
>                 while (!Thread.interrupted()) {
>                     log.trace("wait for fd");
> 
>                     LocalSocket socket = localServerSocket.accept();
> 
>                     if (!executorService.isShutdown() && !executorService.isTerminated()) {
>                         executorService.execute(() -> {
>                             try {
>                                 DataInputStream inputStream = new DataInputStream(socket.getInputStream());
>                                 DataOutputStream outputStream = new DataOutputStream(socket.getOutputStream());
> 
>                                 int fd = inputStream.readInt();
> 
>                                 int success = 1;
>                                 if (!mainService.protect(fd)) {
>                                     log.error("protect failed");
>                                 } else {
>                                     success = 0;
>                                 }
> 
>                                 outputStream.writeInt(success);
> 
>                                 socket.close();
>                             } catch (IOException e) {
>                                 e.printStackTrace();
>                             }
>                         });
>                     }
>                 }
> 
>                 log.info("loop broke");
>             } catch (IOException e) {
>                 e.printStackTrace();
>             }
> 
>             log.info("protector exit");
>         } while (mainService.isAlive());
>     }
> }
> ```

Thank you. I see. In fact, I'm very curious about your app. Every time you connect, you can turn on the Tun (VPN flag) in seconds. But you also restart the process every time. I've seen that it takes about 2s to start a new process every time. How do you do that
