### ISSUE TITLE
some questions!

### ISSUE THREAD

**Issue by mokhtarabadi** [eycorsican/aleaf#2]
Why using Unix socket for protection socket in android, while can use simple JNI callback?

I successfully built leaf for android with rusttls and ring, and test in many android versions and devices including emulators, I didn't see any errors, why you using OpenSSL, is its effect on performance?

Currently, I using leaf in another process by using Runtime.exec() so I can stop it every time the user presses the stop button, but I'm a little confused with this repository how I can stop leaf and also the VPN service?

**Comment by eycorsican** [comment]
Simply because the RPC method is easier. It's not obvious to me how we can call java from rust code which itself is a procedure calling from java.

There are 2 target arm64-v8a and x86_64, the former is using ring/rustls, the latter is using openssl simply because ring doesn't support x86_64 android targets.

You simply [stop the VPN service](https://developer.android.com/reference/android/app/Service#stopSelf()). leaf is invoked as a static library (instead  of an executable), it's running in a thread of the VPN service.

**Comment by mokhtarabadi** [comment]
Yes RPC is very simpler than JNI!

I think I tested it in x86_64 android emulator with API 29 (vless_ws_tls with rustls and ring) and works, I'll test it again...

Yes I know I can stop service but I speaking about gracefully shutdown the leaf, threads can be alive after service destroyed, and also called close method on VPN service file descriptor (ParcelFileDescriptor) didn't work if something works on tun interface (I mean rust-tun) I test it in many android versions (android 16-20 other app processes is still alive if main process killed) 
I think ideal is stop leaf first and wait until all leaf threads finished then stop service and file descriptor 

I didn't know rust too much, how I can stop tokio runtime? (https://github.com/eycorsican/leaf/blob/021391608cdb6d5ef16dfb1146f10daf61423885/leaf-bin/src/main.rs#L127)

**Comment by eycorsican** [comment]
Graceful shutdown is absolutely a needed feature, there's a discussion [here](https://github.com/eycorsican/leaf/discussions/65), I'm considering implement it as a RESTful API instead of using FFI.

**Comment by mokhtarabadi** [comment]
I checked my implementation in android emulator x86_64 (leaf built using ndk 22.0.7026061 and API 21) with vless_websocket_tls and everything works like a charm!

command to build leaf-bin `cargo ndk --manifest-path leaf-bin/Cargo.toml -t x86_64 -p 21 build --release --no-default-features --features "leaf/config-json leaf/inbound-socks leaf/inbound-http leaf/outbound-direct leaf/outbound-drop leaf/outbound-tryall leaf/outbound-vmess leaf/outbound-tls leaf/outbound-ws leaf/outbound-chain leaf/ring-aead leaf/rustls-tls"`

I don't have real 64-bit android device to test it :D

**Comment by eycorsican** [comment]
Well, I retry with ring/rustls and it indeed builds! No idea why my early attempts failed.

**Comment by mokhtarabadi** [comment]
Now leaf can shutdown buy using api, please implement stop, test and reload config in this project, thanks

**Comment by mokhtarabadi** [comment]
Hey @eycorsican, where are you, man? are you safe?
