### ISSUE TITLE
how can add ipv6 support?

### ISSUE THREAD

**Issue by mokhtarabadi** [eycorsican/aleaf#3]
I seems aleaf didn't support ipv6, how I can add this, it's enough to add ipv6 route in VpnBuilder?

**Comment by mokhtarabadi** [comment]
Now I see ip6 support in leaf project
But I see it will enabled by setting environment variables, how I can enable in static library (leaf-ffi) without edition leaf source code(default options)

**Comment by mokhtarabadi** [comment]
@eycorsican mean something like .env file

**Comment by eycorsican** [comment]
Is [this](https://github.com/eycorsican/aleaf/blob/e980721d0231c1f1d12d002c2f725f5956833513/app/src/main/java/com/leaf/example/aleaf/SimpleVpnService.kt#L104) answers your question?

**Comment by mokhtarabadi** [comment]
I didn't care about android.system.Os.setenv
I'll test it

**Comment by mokhtarabadi** [comment]
works, thanks
