### ISSUE TITLE
open mmdb file /system/bin/geo.mmdb failed

### ISSUE THREAD

**Issue by wangjinwei0806** [eycorsican/aleaf#6]
配置文件中有如下規則
EXTERNAL, mmdb:cn, Direct

2021-04-19 13:30:49.117 4095-4175/com.leaf.example.aleaf V/leafmempSecscertlocsP: [2021-04-19 13:30:49][WARN] open mmdb file /system/bin/geo.mmdb failed

2021-04-19 13:31:03.796 4095-4175/com.leaf.example.aleaf V/leafmempSecscertlocsP: [2021-04-19 13:31:03][INFO] [tcp] [tun] [Fallback] [226ms] www.ip.cn:443

//我寫入到配置文件根目錄，浏览器测试ip.cn ，直接走了Fallback，但是我在ios 那边却走的Direct
![image](https://user-images.githubusercontent.com/3974508/115186234-edbd7880-a113-11eb-91d0-a2299ac14600.png)

按着这个readme，参考以下连接
https://github.com/eycorsican/leaf/blob/master/README.zh.md#mmdb
https://github.com/eycorsican/ileaf/issues/14#issuecomment-751782111

**Comment by wangjinwei0806** [comment]
按着这个readme
https://github.com/eycorsican/leaf/blob/master/README.zh.md#mmdb，目录应该没问题的

**Comment by eycorsican** [comment]
用 `ASSET_LOCATION` 指定目录：https://github.com/eycorsican/leaf/issues/124

**Comment by wangjinwei0806** [comment]
sorry ，我各种尝试都不行 写入configContent

测试1
ASSET_LOCATION = /data/user/0/com.leaf.example.aleaf/files/config/
EXTERNAL, mmdb:cn, Direct

测试2
EXTERNAL, mmdb: /data/user/0/com.leaf.example.aleaf/files/config/geo.mmmdb:cn, Direct
都不行

**Comment by wangjinwei0806** [comment]
sorry ,test success
