### ISSUE TITLE
leafandroid.so怎么获取

### ISSUE THREAD

**Issue by huqiyu** [eycorsican/aleaf#7]
.so文件怎么获取 
并且build.sh debug是报error: failed to run custom build command for `ring v0.16.20`错误

**Comment by wangjinwei0806** [comment]
see https://github.com/eycorsican/aleaf/actions/runs/747697441

**Comment by wizos** [comment]
还是会因为 failed to run custom build command for `ring v0.16.20` 而失败

**Comment by LaoHuan** [comment]
我的mac也是提示这个。应该怎么处理。求解答

**Comment by wangjinwei0806** [comment]
用github 编译好点，如果用其它环境，一头雾水

**Comment by LaoHuan** [comment]
最新的so为什么比之前的大了，我看之前一个15.现在的30，so包大小翻倍了喃

**Comment by LaoHuan** [comment]
> 用github 编译好点，如果用其它环境，一头雾水

请问你的看youtube会卡顿吗？我用同类的比较，别个就很流畅，这个用一会儿就会卡

**Comment by wangjinwei0806** [comment]
> > 用github 编译好点，如果用其它环境，一头雾水
> 
> 请问你的看youtube会卡顿吗？我用同类的比较，别个就很流畅，这个用一会儿就会卡

没注意这个
